runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /fonts
  static_dir: svg
- url: /templates
  static_dir: html
- url: /.*
  script: blog_routes.app

libraries:
- name: jinja2
  version: latest